### ISSUE TITLE
Improve documentation of the shrink parameter going into pmx_plot_eta_box

### ISSUE THREAD

**Issue by tynesjo** [ggPMXdevelopment/ggPMX#100]
Just note that the parameter must be a named list:
for example, the following is valid:
`ctr %>% pmx_plot_eta_box(shrink = list(fun="sd"))`
whereas the following is not valid:
`ctr %>% pmx_plot_eta_box(shrink = list("sd"))`

**Comment by baltcir1** [comment]
Dear Johannes, thanks for raising this! We have users questions on the shrinkage. What is the default function for shrinkage? Is is sd or var? (I never remember)
Thanks!

**Comment by KZRKZR** [comment]
Hi @baltcir1! 
The default values for eta_box plot in config:
```
$is.shrink
[1] TRUE

$shrink
$shrink$fun
[1] "sd"

$shrink$size
[1] 4
```

Best regards,
Kostia
