### ISSUE TITLE
filter does not accept pre-defined strings as input

### ISSUE THREAD

**Issue by margoal1** [ggPMXdevelopment/ggPMX#103]
**This works:** 
`ctr %>% pmx_plot_npde_time(filter = "STUD == 12201")`

**This doesn't work:**
```
filter_string = "STUD == 12201"
ctr %>% pmx_plot_npde_time(filter = filter_string)


Error: operations are possible only for numeric, logical or complex types
```

**Why this would be useful:**
Having this feature work would make it possible to loop over different subgroups to filter by. For example if you wanted to create separate plots for separate studies:
```
for(istud in unique(PKdata$STUD)){
    filter_string = paste0("STUD == ", istud)
    ctr %>% pmx_plot_npde_time(filter = filter_string)
}

Error: operations are possible only for numeric, logical or complex types
```

**Comment by margoal1** [comment]
**Workaround:**

filter_string = "STUD == 12201"
ctr %>% pmx_plot_npde_time(filter = **eval( parse(text = filter_string) )** )

**Would be nice to implement this in the next version of ggPMX so that user does not have to use eval(parse()) workaround**

**Comment by tynsci** [comment]
- @margo
- @margoal1 can not reproduce with current version of ggPMX master branch; looks like filter works normally even if input is a string variable

## Outputs differ with two different filter variables defined as `character`

### Case 1

```{r}
filter_string <- "SEX == 0"
theophylline() %>%
pmx_plot_npde_time(filter=filter_string)
```

Plot:

![Screenshot_from_2022-11-02_16-05-54](https://user-images.githubusercontent.com/90842492/199690135-6d5fe577-c8d4-4b1a-8cff-4b54e20bdbd6.png)


### Case Two

```{r}
filter_string <- "SEX == 1"
theophylline() %>%
pmx_plot_npde_time(filter = filter_string)
```

Plot:


![Screenshot_from_2022-11-02_16-06-26](https://user-images.githubusercontent.com/90842492/199690165-a08460e3-e781-483f-80c0-696d38f93a8e.png)
