### ISSUE TITLE
Monolix flag  "ignored observations" not handled

### ISSUE THREAD

**Issue by combefr1** [ggPMXdevelopment/ggPMX#104]
Hi 
I have in myu dataset a flag "PLACEBO", which indicates all PD measurment during a placebo period (after w 24). these observations are flagged as "ignored observation" in monolix, hence not taken into consideration

In the ggPMX individual plots, the predictions stop at the last observation before placebo (about week 23), but the observations are still shown during the placebo period.

maybe adding a color for these ignored observations?

best
Francois

**Comment by biethbr1** [comment]
@combefr1 : can you clarify for us the flag used in Monolix? Is it labeled as IGNORE which can take the value 0, 1 or 2?  

Thanks!

**Comment by combefr1** [comment]
Hi
it is using the column mmapping "IGNORED OBSERVATION" in monolix, and takes a 0 (keep) or 1 (ignore)

![image](https://user-images.githubusercontent.com/33521747/107993798-4c963280-6fa9-11eb-8f74-60c4445940fe.png)

**Comment by tynesjo** [comment]
fixed by #160
