### ISSUE TITLE
ranges and scale_y_log10 don't work at the same time

### ISSUE THREAD

**Issue by margoal1** [ggPMXdevelopment/ggPMX#106]
**This works:**
`ctr %>% pmx_plot_vpc(ranges = list(y = c(0.01, 500)))`
produces a plot with y limits of 0.01 to 500

**This works:**
`ctr %>% pmx_plot_vpc(scale_y_log10 = TRUE)`
produces a plot with log scaled y axis, with unconstrained y limits (happen to go from 1e-61 to 1e+03 in this case)

**This doesn't work:**
`ctr %>% pmx_plot_vpc(ranges = list(y = c(0.01, 500)), scale_y_log10 = TRUE)`
produces a plot with log scaled y axis, but y limits still go from 1e-61 to 1e+03

Same behavior happens for other plots, e.g. pmx_plot_npde_time, pmx_plot_dv_pred, pmx_plot_eta_cats. 
Option scale_y_log10 = TRUE ignores ranges.

**Comment by sehamsick** [comment]
There is a workaround for this issue, using **ggplot2** syntax:

The following code should work:
`ctr %>% pmx_plot_vpc() + scale_y_log10(limits = c(1,500))`

This should also work for all other plots e.g.:
`ctr %>% pmx_plot_individual() + scale_y_log10(limits = c(1,500))`

**Comment by biethbr1** [comment]
@tynesjo: can we use a permanent fix instead of use the worlaround?
