### ISSUE TITLE
Remove console color coding from nlmixr fit print output

### ISSUE THREAD

**Issue by tynesjo** [ggPMXdevelopment/ggPMX#107]
the print output of nlmixr includes console color coding which does not render in HTML and which cannot be compiled to PDF via latex.

Suggest using `crayon::strip_style` to address this

This problem affects the `nlmixr` vignette.

**Comment by mattfidler** [comment]
You could also set an option instead:

```r
options(crayon.enabled=FALSE)
```

There are some crayon markdown rendering options too, but I don't know them.

**Comment by tynesjo** [comment]
Ok thanks I will test using an option first as that will apply globally within the document and presumably means that `crayon` need not be installed.

**Comment by mattfidler** [comment]
`crayon` is imported by `nlmixr`, so it will need to be installed.  It is in the tidyverse stack, so I don't think it is a problem.
