### ISSUE TITLE
VPC: Cannot set title or change time variable of vpc

### ISSUE THREAD

**Issue by bartech3** [ggPMXdevelopment/ggPMX#110]
The following code did not work in that it did not change the title of the vpc nor the time variable.

```r
ctr %>% 
  pmx_plot_cats(
    "iwres_time",
    cats = "DOSE",
    aess = list(x="TADQBW"), 
    filter = TADQBW < 24 & TADQBW > -2,
    labels = list(title = "IWRES vs TAD", x="Time after last dose (h)"))
```

**Comment by KZRKZR** [comment]
Can't reproduce for standard controller:

```
ctr <- theophylline()
ctr %>%
  pmx_plot_cats(
    "iwres_time",
    cats = "SEX",
    labels = list(title = "IWRES custom title", x="Time after last dose (h)"))
```
![image](https://user-images.githubusercontent.com/10551498/97165189-ff891900-178b-11eb-83e9-495f6a6455e6.png)

**Comment by baltcir1** [comment]
Dear Kostiantyn, 

can you please try and filter in the same time, as in the original ticket above? For example:
ctr <- theophylline()
ctr %>%
  pmx_plot_cats(
    "iwres_time",
    cats = "SEX",
    filter = TIME< 24 & TIME> -2,
    labels = list(title = "IWRES custom title", x="Time after last dose (h)"))

Ideally, it would be good to check also by changing the time variable. Do you have access to other examples with several time columns? Please let us know.

THanks!
Irina

**Comment by KZRKZR** [comment]
Dear Irina, 
tried example with filter
```
ctr <- theophylline()
ctr %>%
  pmx_plot_cats(
    "iwres_time",
    cats = "SEX",
    filter = TIME< 24 & TIME> 10,
    labels = list(title = "IWRES custom title", x="Time after last dose (h)"

))
```
works fine
![image](https://user-images.githubusercontent.com/10551498/97166900-a53d8780-178e-11eb-91bd-2e0d5f437fd7.png)
 I have access only to standard examples in the package. Could you share, please, these examples?

Best regards,
Kostia

**Comment by biethbr1** [comment]
Hi Kostia,

Can you please try with the enclosed example?

```
work_dir <- '~/SVN/ggPMX_doc/USER_EXAMPLES/MLX/2018/14.PK_WITH_ANOTHER_TIME'

# set-up the mlxtran file path
mlxtran_path = file.path(work_dir,"warfarin_PK_project.mlxtran")

# set-up working directory
setwd(work_dir)

# Create controller for PK (default):
ctr = pmx_mlxtran(mlxtran_path)

# iwres versus time
# using standard time column
ctr %>% 
  pmx_plot_iwres_time()

# code below not working anymore!
ctr %>% 
  pmx_plot_cats(
    "iwres_time",
    cats = "sex",
    aess = list(x="TAD"), 
    filter = TAD < 5 & TAD > -2,
    labels = list(title = "IWRES vs TAD", x="Time after last dose (h)"))
```

[14.PK_WITH_ANOTHER_TIME.zip](https://github.com/ggPMXdevelopment/ggPMX/files/5439276/14.PK_WITH_ANOTHER_TIME.zip)

**Comment by KZRKZR** [comment]
Thank you! Will check.

пн, 26 окт. 2020 г., 16:14 biethbr1 <notifications@github.com>:

**Comment by tynesjo** [comment]
@biethbr1 it has been possible to test the code with the data you sent, and the bug is still not reproducible. Below you can find the two graphical outputs (for the `pmx_plot_iwres_time()` and `pmx_plot_cats(..` calls:

![graph1](https://user-images.githubusercontent.com/3072895/106602210-98ca8700-6554-11eb-8f1c-94fa9b69f6d1.png)
![graph2](https://user-images.githubusercontent.com/3072895/106602216-99fbb400-6554-11eb-89b2-a0c38dbd13f1.png)

**Comment by baltcir1** [comment]
Many features of VPC do not work. For example:
- can't remove footnote of VPC (text below the figure starting with "The areas...")
- Can't remove or change the title of VPC by using labels = list(title = "new title")
- ranges feature also doesn't work (via pmxpar = pmx_par(list(ranges = ?!?)), also syntax is not clear)

An example code is given below:
ctr %>% pmx_plot_vpc(bin = pmx_vpc_bin(style = "fixed", fixedBreaks=c(0,13,20,27,40,62,90,100)), # style = "kmeans", n=5
                                    filter = STUDYIDN==102204 & TIME<100, 
                                    #strat.facet = ~MYTRT, facets=list(nrow=1), 
                                    #is.legend = TRUE,
                                    #pmxgpar = pmx_gpar(list(is.footnote = TRUE)),
                                    scale_y_log10 = TRUE,
                                    labels = list(title = "", x="Time (days)",
                                                  y="Iptacopan concentration (ng/ml)"))
Version: 1.2.6

**Comment by tynsci** [comment]
> * can't remove footnote of VPC (text below the figure starting with "The areas...")
- this bug is handled in #193 and associated merge request #218
