### ISSUE TITLE
covariates argument not supported by pmx_plot_eta_cats

### ISSUE THREAD

**Issue by bartech3** [ggPMXdevelopment/ggPMX#122]
The covariates argument is not supported by pmx_plot_eta_cats. It works for pmx_plot_eta_conts.

**To Reproduce**

        ctr %>% pmx_plot_eta_cats(covariates = cats1)

with cats defined as something like 

        cats1 <- pmx_cov(values = as.list(params$cats1))

**Package and platform**
 - Operating system: Linux
 - ggPMX version 1.0

**Comment by tynesjo** [comment]
It is possible to reproduce this issue:
`theophylline() %>% pmx_plot_eta_cats(covariates = pmx_cov(values=list("WT0")))`
produces the same graphical output as
`theophylline() %>% pmx_plot_eta_cats`.

This is not the case if `pmx_plot_eta_covs` is used instead.
