### ISSUE TITLE
Line disappears behind the points when strat.color is used

### ISSUE THREAD

**Issue by sehamsick** [ggPMXdevelopment/ggPMX#138]
**Describe the bug**
Line disappears behind the points when strat.color is used

**Code to reproduce**
```r
ctr <- theophylline()
ctr %>% pmx_plot_dv_ipred() #the line is in front of the points
ctr %>% pmx_plot_dv_ipred(strat.color  = "SEX") #the line is no longer in front of the points
```

**Expected behavior**
The line should always be plotted in front of the points.

**Screenshots**
The line is in front of the points `ctr %>% pmx_plot_dv_ipred()`
![image](https://user-images.githubusercontent.com/58450134/96848552-dcd9c600-1454-11eb-8a0b-89cc8a70aa5b.png)

The line disappears behind the points `ctr %>% pmx_plot_dv_ipred(strat.color  = "SEX")`
![image](https://user-images.githubusercontent.com/58450134/96848783-24f8e880-1455-11eb-95e2-1c6f7551b9e1.png)

**Comment by agstudy** [comment]
Thank you very much for this bug report! Bug well explained with a reproducible example.
