### ISSUE TITLE
Bug with individual plots 

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#145]
**Describe the bug**
The predicted lines start only at the 1st observation and not from the actual administration. This changes the predicted profile in the 1st dosing cycle

**To Reproduce**
Example code used to generate the plot
![image](https://user-images.githubusercontent.com/73995818/98235443-18e74d80-1f62-11eb-93ad-7354cfb0c960.png)

**Expected behavior**
Please see snapshot of individual plot generated in Monolix:
![image](https://user-images.githubusercontent.com/73995818/98235523-31576800-1f62-11eb-93ba-2fddd0416ec0.png)

**Screenshots**
Please see a snapshot of the same plot generated in ggPMX:
![image](https://user-images.githubusercontent.com/73995818/98235565-46cc9200-1f62-11eb-9715-19408692eca4.png)

**Package and platform (please complete the following information):**
 - Operating system: [e.g. Linux, Windows]
 - ggplot2 version
 - ggPMX version [e.g. 1.0

**Comment by tynesjo** [comment]
Fail to reproduce on current development branch version (1.2.1).
![individual-fit-8](https://user-images.githubusercontent.com/3072895/106596290-b398fd80-654c-11eb-8062-8f4f9039aa9f.png)

**Comment by tynesjo** [comment]
@biencan1
An additional investigation shows that this issue was solved by merge request to solve #146 
Below is an output confirming the issue you reported when the fix for 146 was removed:

![1](https://user-images.githubusercontent.com/3072895/106700601-11752600-65dd-11eb-9fbe-0c23dc980f78.png)

**Comment by biencan1** [comment]
@tynesjo @baltcir1 
I can confirm that reading in the reader-hotfix.R (created for issue #146) prior to creating the controller solves the issue. :-)
