### ISSUE TITLE
URGENT - major bug: as default all rows with LIDV=0 dropped in ggPMX?

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#146]
**Describe the bug**
I'm working on response data on a scale from 0 to 41 with 0 being complete suppression. Large proportion of the data has zero values. When generating a number of plots (individual plots, vpc, etc) I noticed that this data was not plotted. I did further investigation to the source and I compared the original data with the data in the controller and noticed that none of the datasets in the controller which includes LIDV contains the observation with zero values.

**To Reproduce**
Comparison or original data vs data in the controler:
![image](https://user-images.githubusercontent.com/73995818/98237955-fb1be780-1f65-11eb-8be7-4f7c25f8c82c.png)

**Expected behavior**
Example of individual plots in Monolix:
![image](https://user-images.githubusercontent.com/73995818/98238068-243c7800-1f66-11eb-924d-501a800ab644.png)

Example of a vpc:
![image](https://user-images.githubusercontent.com/73995818/98240145-484d8880-1f69-11eb-9ed9-17bdd571481f.png)

**Screenshots**
Same plot in ggPMX:
![image](https://user-images.githubusercontent.com/73995818/98238104-2f8fa380-1f66-11eb-9a07-3d197e818907.png)

vpc in ggPMX:
![image](https://user-images.githubusercontent.com/73995818/98240092-366be580-1f69-11eb-9c98-bda4a078970c.png)

**Package and platform (please complete the following information):**
![image](https://user-images.githubusercontent.com/73995818/98239000-8fd31500-1f67-11eb-9983-bd23c2705af9.png)

**Additional context**
Is a work around with ggPMX 1.0 possible? If so it's urgently needed. I suspect all of the diagnostic plots generated in ggPMX are affected.

**Comment by baltcir1** [comment]
Thanks, @biencan1, for raising this issue. Indeed, this was a "quick and dirty" fix of issues with log scale of some plots (eg. DV vs PRED). Basically, what we need here is rather a fix for the situation where the user wants to look at log scale and there are zeros. Can we just keep all data points (NOT filtering those with LIDV==0) and then see what kind of warning or error we get when we use log scales for dv_vs_pred plot?

Dear @tynesjo, would you be so kind and look quickly into this? It might be an easy fix. Please let us know if you have an appropriate example...

**Comment by biencan1** [comment]
@baltcir1 Yes, I see the issue... But I guess in a situation where you have data with zero values you wouldn't be generating plots on log scale?

**Comment by tynesjo** [comment]
@baltcir1 Yes, should be able to investigate during today or Monday

**Comment by mattfidler** [comment]
This should be fixed @biencan1
