### ISSUE TITLE
pmx_plot_iwres_dens plot is missing a legend

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#147]
**Describe the bug**
the pmx_plot_iwres_dens does not have a legend although you plot two different sets of data

**To Reproduce**
ctr %>% pmx_plot_iwres_dens

**Expected behavior**
There should be a legend on top of the plot

**Screenshots**
![image](https://user-images.githubusercontent.com/73995818/98241238-f4dc3a00-1f6a-11eb-946a-82e956a3eb17.png)

**Package and platform (please complete the following information):**
![image](https://user-images.githubusercontent.com/73995818/98241299-0887a080-1f6b-11eb-9b70-5288fd85d550.png)

**Comment by biethbr1** [comment]
Suggest to add the following legend:
Dashed line: Standard Normal Distribution
Continuous line: Observed Distribution
