### ISSUE TITLE
vpc_sim requires dv

### ISSUE THREAD

**Issue by mattfidler** [ggPMXdevelopment/ggPMX#149]
**Describe the bug**
While Simulx can simulate different values than DV, it appears that `vpc_sim` doesn't use the information to infer the dependent variable.  

**To Reproduce**
If I simulate a variable say `Rf_pred` and use the code on the website to create a dataset with `Rf_pred` as an output instead of `DV` then the controller does not run with `vpc_sim`.  A simple renaming of the `Rf_pred` to `DV` fixes the problem.  However, I'm unclear what is needed for multiple endpoint VPCs.

**Comment by baltcir1** [comment]
I confirm that dependent variable needs to have the same name in simulation to the name of the DV in the input modeling dataset. This should be explicitly stated in the documentation. 
"Make sure to use the same name for the dv column in the simulation file as the one used in the input (modeling dataset)." 
I haven't tested the PD part - will do and update you on this.
