### ISSUE TITLE
vpc: plots don't cover the whole range of observed time

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#154]
**Describe the bug**
VPC plots don't cover the whole range of time variable on x-axis. Depending on the binning method used they either cut the observations around start (time>=0) or at the end of observational period. 
Here's an example of a plot generated in ggPMX:
![image](https://user-images.githubusercontent.com/73995818/100548698-783d3280-326e-11eb-95d7-a7a3d932d560.png)

And a plot generated in Monolix:
![image](https://user-images.githubusercontent.com/73995818/100548704-81c69a80-326e-11eb-8ca0-3f9446a573a7.png)

Also binning is suboptimal. 

**To Reproduce**
I can provide code and datasets to reproduce provided plots

**Package and platform (please complete the following information):**
![image](https://user-images.githubusercontent.com/73995818/100548753-ceaa7100-326e-11eb-954b-339d778afbb4.png)

**Comment by biethbr1** [comment]
@tynesjo: can you look at the ggPMX code to understand if there is selection performed by ggPMX to select the range of x-axis?

**Comment by tynesjo** [comment]
Issue reproduced.

The plot attached additionally has individual observations shown:
they do cover an x axis range which extends beyond that of the median and percentiles lines.

![vpc-w-indidividual](https://user-images.githubusercontent.com/3072895/107197220-871d2f80-69eb-11eb-99a7-a27628a41db9.png)

**Comment by baltcir1** [comment]
Hi Johannes,

Thanks for working on this. I suppose the areas span from the middle of the first bin to the middle of the last bin (something like that). There is also an option in the VPC plot to display ticks that show the bins. That may also help to identify the problem.

Best,
Irina

**Comment by baltcir1** [comment]
Problem can be solved by adding an additional bin. I suggest closing this issue.
