### ISSUE TITLE
Lack of reproducibility of vpc plots

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#155]
**Describe the bug**
Upon repeated execution of code generating vpc the plot changes. Each repeated execution of the same code changes the appearance of the plot

**To Reproduce**
![image](https://user-images.githubusercontent.com/73995818/103128409-8166c700-4695-11eb-8d77-a6cfba088d56.png)

**Expected behavior**
Given that no simulation is conducted while generating the code and no modifications of the code were made and it specifies number of bins the same plot should be produced upon each repeated execution.

**Screenshots**
Execution 1:
![image](https://user-images.githubusercontent.com/73995818/103128538-110c7580-4696-11eb-95d7-f6e6558217ca.png)

Execution 2:
![image](https://user-images.githubusercontent.com/73995818/103128542-18338380-4696-11eb-81d2-b6e031634f8a.png)

Execution 3:
![image](https://user-images.githubusercontent.com/73995818/103128546-1c5fa100-4696-11eb-8af5-04eb851ea0d1.png)

Execution 4:
![image](https://user-images.githubusercontent.com/73995818/103128560-25e90900-4696-11eb-8c3b-d594e5cbf45c.png)

**Package and platform (please complete the following information):**
![image](https://user-images.githubusercontent.com/73995818/103128627-53ce4d80-4696-11eb-89e2-471915e4815c.png)

**Comment by mattfidler** [comment]
You need to specify the seed in simulx.

http://simulx.webpopix.org/userguide/seed/

The documentation should probably be updated.

**Comment by mattfidler** [comment]
Perhaps a simulation is run... If not then it is a bug

**Comment by biencan1** [comment]
The simulation file for vpc is run by a separate simulx script and not repeated. Each of the presented plots is created with the same controller (not recreated at each execution), simply by re-executing the vpc command.

**Comment by baltcir1** [comment]
Strange... must be something with the binning... we’ll follow up.

Sent from my iPhone

On 25 Dec 2020, at 18:28, biencan1 <notifications@github.com> wrote:

﻿

The simulation file for vpc is run by a separate simulx script and not repeated. Each of the presented plots is created with the same controller (not recreated at each execution), simply by re-executing the vpc command.

**Comment by tynesjo** [comment]
Confirm it has been possible to reproduce this issue using the controller from `theophylline()`.

The example below returns inconsisent graph if the `set.seed(1)` line is commented out, therefore suggesting that there is some randomness which should be controlled for reproducibility. For this particular example the differences in data do not lead to visually detectable differences, but they are still there.

```
test155 <- function() {
  ctr = theophylline()
  llply(1:2, . %>% {
    set.seed(1)
    pmx_plot_vpc(
      ctr,
      bin=pmx_vpc_bin(style="kmeans", n=10, within_strat=TRUE),
      obs=pmx_vpc_obs(show=FALSE),
      strat.facet="SEX",
      is.draft=FALSE,
      use.abbrev=TRUE,
      facets=list(scales="free")
    )} %>%
    {.[["data"]]}
  ) %T>%
  {print(all_equal(.[[1]], .[[2]]))}
}
```
