### ISSUE TITLE
Add facets to pmx_plot_cats

### ISSUE THREAD

**Issue by baltcir1** [ggPMXdevelopment/ggPMX#162]
We would like to have the possibility to specify nb of rows and columns for `pmx_plot_cats()`, in a similar way as for `pmx_plot_individual()`. To avoid the following situation (when many strata exist):
![image](https://user-images.githubusercontent.com/25454764/107500956-11ee5d80-6b97-11eb-8b30-bbe1767c8d97.png)

The target syntax would be: 
`pmx_plot_cats("dv_pred", cats="DoseStr", facets = list(nrow = 4, ncol = 4))`

**Comment by tynsci** [comment]
- this has been implemented in pull request forthcoming now

**Example Code**

```
theophylline() %>% pmx_plot_cats("dv_pred", cats="AGE0", facets=list(nrow=4))
```

**Screenshot of Plot**

![facets](https://user-images.githubusercontent.com/90842492/169663967-6cf6b50e-eaec-45d6-a091-19ead51e05ac.png)
