### ISSUE TITLE
VPC: option is.footnote=FALSE not working  

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#193]
**Describe the bug**
Option is.footnote=FALSE not working. Cannot remove the footnote

**To Reproduce**
```
ctr <- theophylline()
ctr %>% pmx_plot_vpc(type='scatter',is.footnote=FALSE)
```

**Expected behavior**
Footnote "The areas represent..." at the bottom of the figure should not appear anymore

**Package and platform (please complete the following information):**
 - ggPMX version 1.2.6

**Comment by baltcir1** [comment]
By searching in the code, I found that this is not a simple footnote as in other plots, but a vpc_footnote. So we would need a new argument (is.caption) that would allow switching off this text. Currently, it's always on (see code extract below).
plot_pmx.pmx_vpc <- function(x, dx, ...) {
  x <- x %>% 
    vpc_legend. %>%
    vpc_footnote.
  
  if (!is.null(x$db)) p <- vpc.plot(x)
  plot_pmx(x$gp, p)
}

**Comment by baltcir1** [comment]
Thanks to Matt, we have a way to remove the caption and title by using the labs() statement of ggplot2. Example:
ctr %>% pmx_plot_vpc(scale_y_log10 = TRUE,
                                      labels = list(title = "", x="Time (days)", y="Iptacopan concentration (ng/ml)")) +
              labs(title = NULL, subtitle=NULL, caption=NULL)

This does the job, I close the ticket.
