### ISSUE TITLE
nlmixr controller not working

### ISSUE THREAD

**Issue by mattfidler** [ggPMXdevelopment/ggPMX#209]
Thank Dr. @mattfidler, this problem was solved as your suggestion.

I had an additional error with my dataset although this task worked with the `vpc` function. I prepare an example that illustrates it. 

I appreciate your time to consider me. If needed, I can create a new issue for this bug.

Thank you so much again. 
Best regards, Tien.

```
library(tidyverse)
library(RxODE)
library(nlmixr)
library(ggPMX)

# Data' purpose illustrates the error and my data set
df = tibble(
  ID = c(rep(1, 6), rep(2, 6)),
  TIME = c(0.00, 12.11, 18.41, 23.89, 36.00, 43.51, 0.00, 12.00, 20.00, 24.00, 36.80, 45.00),
  AMT = c(1000, 1000, NA, 1000, 1000, NA, 1000, 2000, NA, 1000, 1000, NA),
  DUR = c(2.5, 2.5, NA, 2.5, 2.5, NA, 2.5, 2.5, NA, 2.5, 2.5, NA),
  DV = c(NA, NA, 3.0, NA, NA, 9.6, NA, NA, 7.0, NA, NA, 2.8),
  WT = c(rep(55, 6), rep(48, 6))
) %>% 
  mutate(EVID = ifelse(is.na(DV), 1, 0))

model = function() {     
  ini({
    tvCl <- c(0, 4, Inf)
    tvVc <- c(0, 48, Inf)
    
    eta.Vc ~ 0.62
    prop.sd <- 0.051529     
           
  })
  model({
    Cl <- tvCl
    Vc <- tvVc*(WT/70)*exp(eta.Vc)
    
    # dynamical system
    linCmt() ~ prop(prop.sd) 
  })
}

fit = nlmixr(model, df, list(print=0), est="posthoc")

# Output with vpc() as figure below
p1 = vpc(fit, pred_corr = TRUE, show = list(obs_dv = T))
```
Output with `vpc()` function
![image](https://user-images.githubusercontent.com/68368676/163517159-ab5f1ffe-c4c3-4e50-8383-4835df044cd5.png)

Error message with `vpc` in `ggPMX`:
```
p = pmx_nlmixr(fit) %>% pmx_plot_vpc()
#add npde
#Compiling NPDE model...done 
#done
#Compiling VPC model...done
#done (0.57 sec)
#Error in data.frame(PARAM = row.names(pars), VALUE = pars$Estimate, SE = pars$SE,  : 
#arguments imply differing number of rows: 3, 0
```
```
p
#Error: object 'p' not found
```

_Originally posted by @namtien0312 in https://github.com/ggPMXdevelopment/ggPMX/issues/208#issuecomment-1099839078_

**Comment by mattfidler** [comment]
@namtien0312  This should be fixed in the development version of `ggPMX`

```r
remotes::install_github("ggPMXdevelopment/ggPMX")
````

**Comment by namtien0312** [comment]
Thank Dr. Fidler for your help. And sorry for the late response due to personal reasons.

The issue could be solved with the update.
Tien.

**Comment by mattfidler** [comment]
No problem.  I get delayed response.
