### ISSUE TITLE
Error importing nlmixr model

### ISSUE THREAD

**Issue by filippo-ciceri** [ggPMXdevelopment/ggPMX#212]
Hello,

I am trying to import a nlmixr model using the command `pmx_nlmixr`, however I get the following error:

`Error in setDT(sim_data) : Argument 'x' to 'setDT' should be a 'list', 'data.frame' or 'data.table'`

Any idea of what could be the problem here?

Thanks

Filippo

**Comment by mattfidler** [comment]
Without a reproducible example, it is hard to figure out

**Comment by filippo-ciceri** [comment]
Thanks for the quick reply. I was trying to perform VPC on a nlmixr model, but I eventually used the `vpc.ui` function from the `nlmixr` package. Everything worked well (after converting the ID column from factor to numeric).
