### ISSUE TITLE
Force read&write rights for skeleton.Rmd file when producing diagnostics report

### ISSUE THREAD

**Issue by baltcir1** [ggPMXdevelopment/ggPMX#245]
Version 1.2.6: issue when producing two diagnostic reports within the same R session (for example when working with a PKPD model and having a template for PK and another template for PD).

It seems that the Rmd template is stored at the following location:
`/scratch/baltcir1/RtmpeFTNuy/standing/skeleton/skeleton.Rmd`

The rights of this file seem to be copied from the rights of the source Rmd file. In the case of a custom (user-defined) template **under source control**, `skeleton.Rmd` has only read rights, so when the PD controller needs to overwrite skeleton.Rmd, it can't. 

**Proposed solution**
- can we force `skeleton.Rmd` to have read and write rights by default?

**Comment by mattfidler** [comment]
@baltcir1 #247 should work
