### ISSUE TITLE
sim_blq read in correctly for Monolix 2019R2, 2020R1 and 2022R2 but not used in any of the plots

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#255]
In Monolix 2019R2, 2020R1 and 2022R2 there are no issues with *reading* in `sim_blq` data, but they are not used in plotting to substitute DV values for censored data.  

Example code run after creating controller:
```
ctr %>% pmx_plot_iwres_ipred (bloq=pmx_bloq(cens="BLOQ",colour="blue",size=1),
                              strat.facet = ~TRT,
                              use.abbrev = TRUE,
                              is.draft=FALSE,
                              facets=list(scales="free_x",nrow=1),
                              labels = list(title = "IWRES vs IPRED by dose"))
```
Produces following plot:
![image](https://user-images.githubusercontent.com/73995818/186717164-02be7fbd-c20c-4830-9a2a-c80b695064e4.png)

While the plot should look more like this:
![image](https://user-images.githubusercontent.com/73995818/186717195-77608fb3-2d49-4a7b-a1f1-54fb25d5a4e6.png)

When checking the controller the simulated values seem to be loaded fine but under “bloq”: type `NULL` and value reads “Pairlist of length 0” (see snapshot below). Is that correct?
![image](https://user-images.githubusercontent.com/73995818/186856625-65de36d2-71ef-413a-81e1-34610f2f7c5e.png)

`ggPMX 1.2.8` was used using following R-module: `R 4.1.0 Base`.

Monolix run outputs and R scripts available to recreate the issue

**Comment by tynsci** [comment]
- it has been possible to reproduce the bug
- debugging in progress

**Comment by tynsci** [comment]
@biencan1

## Data substition for simulated BLOQ

- data substition for IWRES vs IPRED plot would be based on the following logic:
  - `IWRES=ifelse(as.logical(BLOQ), iwRes_mode_simBlq, IWRES)`

## Resulting Plot

![iwres_sim_blq](https://user-images.githubusercontent.com/90842492/199452669-f93b0c4e-e1e4-4a80-8d4c-5545a358dcf9.png)

## Next

- implement code change in a pull request

**Comment by tynsci** [comment]
@biencan1

- see above pull request #285  which addresses the issue

## Assumptions

- npde, iwres and pwres data are the data types which may need to be copied from simulations
- these data types are available with "_mode" suffix
   - should "mean" ever be used, or would it be available, if so, how should a choice between mean and mode be made: a new parameter?

## Challenges

- there appears to be no data in the package under `inst` which allows this to be tested (no [iwRes,pwRes,npde]_mode_simBlq columns)

**Comment by biencan1** [comment]
I suggest to use the mode_simBlq only (without giving the choice between the mean and the mode). However, it should be made clear in the documentation that the mode_simBlq is used.

**Comment by baltcir1** [comment]
sim_blq still doesn't work.

**Comment by mattfidler** [comment]
Not fixed by #365

**Comment by mattfidler** [comment]
## First issue with BLQ

This is hard coded in the yaml file:

https://github.com/ggPMXdevelopment/ggPMX/blob/ee9a72d754e13d5d3f5145a6daf41409da4089ae/inst/templates/mlx18/standing.ipmx#L10

It shouldn't be.  It is based on endpoint, and should match what you are pulling in for the endpoint.  The default should be `y` which is the typical endpoint for monolix single endpoint models (though in truth this can be arbitrary and is for models coming from other sources like `babelmixr2` or edited manually).

## Second issue with BLQ

Currently the DVs are not replaced with the simulated values; Currently it actually replaces the DV with nothing.  The default DV is still the `LLOQ` value which was in the input dataset, and doesn't match the simulated BLQ dataset from the monolix files.

**Comment by mattfidler** [comment]
@tynesjo if you need to have some screen sharing we can show you what the issue is and which columns you need to grab.
