### ISSUE TITLE
Is it possible to re-order levels of covariates and stratification variables?

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#257]
Is there an easy way to re-order levels of categorical covariates and stratification variables when creating controller?

I tried this and it didn’t work:
```
my_settings = pmx_settings(
    use.labels = TRUE, #to substitute pre-defined labels with custom
    is.draft = TRUE,
    cats.labels=list(
        SEX=c("1"="M","2"="F"),
        ASIAN=c("0"="No","1"="Yes"),
        CUINDN=c("0"="Neg","1"="Pos"),
        TRT=factor(levels=c("24mg q4w" ="24mg q4w" ,"72mg q4w"="72mg q4w","120mg s.d."="120mg s.d.", 
                               "240mg q4w"="240mg q4w")
        )
    )
)  #### doesn't work
```

I managed to manually re-order them in the controller:

```
ctr$data$sim$TRT<-factor(
    ctr$data$sim$TRT,
    levels=c("24mg q4w" ="24mg q4w" ,"72mg q4w"="72mg q4w",
        "120mg s.d."="120mg s.d.", "240mg q4w"="240mg q4w")
)

ctr$data$input$TRT <- factor(ctr$data$input$TRT,
    levels=c("24mg q4w" ="24mg q4w" ,"72mg q4w"="72mg q4w",
        "120mg s.d."="120mg s.d.",   "240mg q4w"="240mg q4w")
)
```

What seemingly worked:

![image](https://user-images.githubusercontent.com/73995818/186860070-5960fa0f-0d74-48e4-8551-2bf4dde9e1b4.png)

But, when generating a facetted plot the order of the panels did *not* correspond to the levels:

```
ctr %>% pmx_plot_iwres_ipred (bloq=pmx_bloq(cens="BLOQ",colour="blue",size=1),
                              strat.facet = ~TRT,
                              use.abbrev = FALSE,
                              is.draft=FALSE,
                              facets=list(scales="free_x",nrow=1),
                              labels = list(title = "IWRES vs IPRED by dose"))
```

![image](https://user-images.githubusercontent.com/73995818/186860104-51c336cb-ad22-4b64-8568-ac667a7329ed.png)

Generated with ggPMX 1.2.8

**Comment by tynsci** [comment]
- a the moment there is no way to change factor levels at controller creation time.
- the order of factors in a facet plot are determined by the data contained in the `predictions` data frame

Hence, you can change the order of facet panels by changing the factor specification for columns in `predicitions`

### Example

```
  ctr <-  pmx_mlxtran(file_name=MLXTRAN_FILE)

  ctr[["data"]][["predictions"]][["TRT"]] <-
    factor(ctr[["data"]][["predictions"]][["TRT"]],
      levels=c("24mg q4w" , "72mg q4w", "120mg s.d.", "240mg q4w"),
      labels=c("24mg q4w" , "72mg q4w", "120mg s.d.", "240mg q4w")
    )

  pmx_plot_iwres_ipred(ctr, strat.facet=~TRT)
```
#### Result using your TRT example

![out_factors](https://user-images.githubusercontent.com/90842492/198200920-1aca8150-eba2-4918-8fea-f04f0e7f6133.png)

#### Next

- will make this clearer in documentation via a pull request

**Comment by biencan1** [comment]
That’s brilliant, should we add this to the documentation?

Best regards, Mit freundlichen Grüssen,

Andrzej Bienczak, PhD MPharm MSc
Senior Principal Pharmacometrics Scientist
PMX Immunology

Associate CDD Rotator – Cosentyx GCA

T  +41 61 324 2636
***@***.******@***.***>

Novartis Pharma AG
Square 3 WSJ-174.1
CH-4056 Basel

**Comment by tynsci** [comment]
> That’s brilliant, should we add this to the documentation?

- **Yes**, see pull request #282  @biencan1
