### ISSUE TITLE
What do ignored observations in individual plots represent?

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#260]
Following code was used:
```
ctr %>% pmx_plot_individual(
  pred_line = list(color = "red", alpha = 0.5),
  which_pages=1,
  filter = TRT == "24mg q4w",
  labels=list(title="Individual fits for 24 mg arm (subset)",
  y="Observed conc. (ug/mL)",
  x="Time after first dose (days)")
)     
```
To produce following plot:
![image](https://user-images.githubusercontent.com/73995818/186869501-17447542-25d0-40be-8ec0-f0bff2fa4b84.png)

Plot indicates that some observations were ignored but no observations are ignored in the model fitting. The dataset contains however BLOQ (censored data) which don’t correspond to the ignored observations from the plot above.

Same plot with flagged BLOQ observations:
```
ctr %>% pmx_plot_individual(
  bloq=pmx_bloq(cens="BLOQ"),
  pred_line = list(color = "red", alpha = 0.5),
  which_pages=1,
  filter = TRT == "24mg q4w",
  labels=list(title="Individual fits for 24 mg arm (subset)",
  y="Observed conc. (ug/mL)",
  x="Time after first dose (days)")
)
```
![image](https://user-images.githubusercontent.com/73995818/186869609-8d52a9e7-d89d-4bb6-8b5b-7843ea193bf2.png)

Legend still contains “ignored”, although no ignored samples are highlighted on the plots.

Generated with ggPMX 1.2.8

**Comment by tynsci** [comment]
- some observations are being classified as *ignored* when their timestamp equals the maxValue
-  pull request addresses this and has such points classified as *accepted*

### Result using modified code

![Screenshot_from_2022-10-07_11-03-27](https://user-images.githubusercontent.com/90842492/196093410-6c755c59-3e17-4bf9-9ca9-8b89896c814b.png)
