### ISSUE TITLE
Sim_blq – error messages when creating controller for datasets without censored data

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#261]
When creating a controller for a model run on a dataset without censored data the console *displays error messages* even though `sim_blq = FALSE` is passed during controller creation: 

![image](https://user-images.githubusercontent.com/73995818/186898144-967dcfd5-1fbc-43f3-b679-f799c7de710a.png)

Generated with ggPMX 1.2.8

**Comment by tynsci** [comment]
- confirm it has been possible to *reproduce* the error
- working on a fix
