### ISSUE TITLE
When creating a controller ggPMX is dropping large portion of the data: ggPMX 1.2.8 (but also earlier versions)

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#262]
### Example 1: ER model, only response variable fitted. DV values contain zero

1)  plot generated using ggPMX function:
`ctr %>% pmx_plot_npde_time`
 
![image](https://user-images.githubusercontent.com/73995818/186907334-d6cf4b75-12f6-435b-8033-61f92674cf96.png)

2) plot recreated by reading in data from controller

```
dat2plot<-ctr$data$predictions

ggplot(dat2plot,aes(x=TIME,y=NPDE)) +
  geom_point()+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
``` 
![image](https://user-images.githubusercontent.com/73995818/186907370-a361378d-b9d4-4f89-a25a-94f6c585fb12.png)

3) plot recreated by reading in directly Monolix outputs
plot source data: 

```
ordat2plot<-read.csv(
  file.path(model.dir,model,'ChartsData/ScatterPlotOfTheResiduals/LIDV_residuals.txt'),sep=','
)

ggplot(ordat2plot,aes(x=time,y=npde)) +
  geom_point()+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```

![image](https://user-images.githubusercontent.com/73995818/186907410-cae62163-513b-4e31-8cc5-679655cc3735.png)

 

### Example 2: PopPK model, dataset contains censored values

1)  plot generated using ggPMX function:

`ctr %>% pmx_plot_npde_time`
 
![image](https://user-images.githubusercontent.com/73995818/186907446-d5296eec-999c-44c6-922e-aa74e6da1f93.png)

2) plot recreated by reading in data from controller

```
dat2plot<-ctr$data$predictions

ggplot(dat2plot,aes(x=TIME,y=NPDE)) +
  geom_point()+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```

![image](https://user-images.githubusercontent.com/73995818/186907478-d051edbf-91e7-4c4e-98cc-24270287620d.png)

3) plot recreated by reading in directly Monolix outputs
plot source data 

```
ordat2plot<-read.csv(file.path(model.dir,model,'ChartsData/ScatterPlotOfTheResiduals/LIDV_residuals.txt'),sep=',')

ggplot(ordat2plot,aes(x=time,y=npde)) +
  geom_point()+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```
![image](https://user-images.githubusercontent.com/73995818/186907508-e52fddf3-79a9-4601-95c3-cbf5318ae401.png)

Dropping of zero or BLOQ values doesn’t seem to be the source of the problem:
 different fill for BLOQ data

```
ggplot(ordat2plot,aes(x=time,y=npde)) +
  geom_point(aes(color=factor(censored)))+
  scale_colour_manual(values = c("0"="black","1"="blue"))+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```

![image](https://user-images.githubusercontent.com/73995818/186910592-7e204546-d2a4-425f-b21a-3ea9ad6f42d6.png)

 
 filter out censored data

```
ggplot(filter(ordat2plot,censored==0),aes(x=time,y=npde)) +
  geom_point()+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```

![image](https://user-images.githubusercontent.com/73995818/186910625-cb438e23-db54-4e45-8cbe-d42bb81dd552.png)

replot using simulated BLOQ
```
ggplot(ordat2plot,aes(x=time,y=npde_simBlq)) +
  geom_point(aes(color=factor(censored)))+
  scale_colour_manual(values = c("0"="black","1"="blue"))+
  geom_smooth(se = FALSE,color="red")+
  theme_bw()
```

![image](https://user-images.githubusercontent.com/73995818/186910662-f84d5bb5-5a5e-49d6-8619-09132fc29f52.png)

**Comment by biencan1** [comment]
**Feedback from Lixoft**: rounding all columns of the dataset to 6 significant digits before using it in Monolix will solve the issue.  In the next version, we will increase the number of significant digits in the output to resolve this problem.

**Comment by biencan1** [comment]
After testing the work around of rounding to 6th significant digit seems to have resolved the issue. See snapshot below as example.

Original dataset:
![image](https://user-images.githubusercontent.com/73995818/189321221-eeab028a-87c9-49a1-bb73-52140e8eefbd.png)

ctr$data$predictions created from this model fit (some time points dropped):
![image](https://user-images.githubusercontent.com/73995818/189321573-26a72337-63db-416c-85aa-82f8355c93bd.png)

ctr$data$predictions created from a run with a modified data set where rounding was applied to time variable using mutate(TIME=signif(TIME,6))
![image](https://user-images.githubusercontent.com/73995818/189321822-057704ba-fe9e-4156-8a65-fece630bf8c1.png)

**Comment by tynsci** [comment]
@biencan1

- closing this since it is an issue with Monolix
- feel free to reopen if you think something should be done with `ggPMX` at this time to address the problem
