### ISSUE TITLE
Controller creation does not work when multiple end points in the model (ggPMX 1.2.8)

### ISSUE THREAD

**Issue by biencan1** [ggPMXdevelopment/ggPMX#264]
Controller creation does not work when multiple end points in the model (ggPMX 1.2.8). I fitted a PKPD model with two end points: 1st PK concentrations (left censored, i.e., with blq-s), and, 2nd response variable. The dependent variable name in the dataset is `LIDV`, `DVID` is used to distinguish the end points. 

I was unable to generate the controller for either of the end points. Please see below the snap shot of code execution in R:

![image](https://user-images.githubusercontent.com/73995818/189614991-4a506573-673b-4897-bab6-8281147e7e06.png)

I suspect the underlying issue might be that in all datasets in Charts Data LIDV is renamed to y1 for the first end point and y2 for the 2nd end point.

**Comment by baltcir1** [comment]
Can you please use the argument call = TRUE in pmx_mlxtran and check how the various arguments were assigned? Then please use pmx_mlx() to create the controller. I think you also need to match the vpc simulation outputs.
Happy to help you debug that issue later this week.

**Comment by biencan1** [comment]
I found the source of the error. When fitting 2 end points Monolix renames them to y1 and y2 independent how the dependent variable is named in the dataset. Because of this when running simulations for vpc the dependent variables are named y1 or y2 rather than same as in the original dataset (in this case LIDV). Renaming the simulated endpoint name in the simulation file to LIDV solved the issue.

**Comment by baltcir1** [comment]
There you go! I had that in mind.. cause experienced the same issue as you before. We should put this in the doc!
