### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by mattfidler** [ggPMXdevelopment/ggPMX#275]
<html>
<body>
<div class="gE iv gt" style="font-size: 0.875rem; padding: 20px 0px 0px; cursor: auto; color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline">

Prof Brian Ripley | Prof Brian Ripley | 12:15 AM (11 hours ago) |   |  
-- | -- | -- | -- | --
Prof Brian Ripley
to me, CRAN | to me, CRAN
to me, CRAN

</div><div id=":l0" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class="" style="color: rgb(34, 34, 34); font-family: &quot;Google Sans&quot;, Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aHl" style="margin-left: -38px;"></div><div id=":j4" tabindex="-1"></div><div id=":jx" class="ii gt" jslog="20277; u014N:xr6bB; 4:W251bGwsbnVsbCxbXV0." style="direction: ltr; margin: 8px 0px 0px; padding: 0px; position: relative; font-size: 0.875rem;"><div id=":j8" class="a3s aiL " style="font: small / 1.5 Arial, Helvetica, sans-serif; overflow: hidden;">Dear maintainer,<br><br>Please see the problems shown on<br>&lt;<a href="https://cran.r-project.org/web/checks/check_results_ggPMX.html" rel="noreferrer" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://cran.r-project.org/web/checks/check_results_ggPMX.html&amp;source=gmail&amp;ust=1666370403594000&amp;usg=AOvVaw1r3NOSGnio8VPsp5iko3DE" style="color: rgb(17, 85, 204);">https://cran.r-project.org/we<wbr>b/checks/check_results_ggPMX.<wbr>html</a>&gt;.<br><br>Please correct before 2022-11-03 to safely retain your package on CRAN.<br><br>The CRAN Team</div></div></div>
</body>
</html>

**Comment by mattfidler** [comment]
@tynesjo can we try to get this all before we are kicked off of CRAN.  

I will work on the `nlmixr2` piece.

**Comment by tynsci** [comment]
@mattfidler confirmed, will work on this

**Comment by tynsci** [comment]
> @tynesjo can we try to get this all before we are kicked off of CRAN.
> 
> I will work on the `nlmixr2` piece.

@mattfidler 
- the only test failing is `nlmixr-test` in `tests/testthat/test-nlmixr.R` on two flavors
  - these follow a `skip_n_cran()` line since 9be295a88d21f998c86e8541980b21c79740d8ac
- should they worked on; or does it more properly belong to `nlmixr2` workflow?

**Comment by tynsci** [comment]
@mattfidler in case any further input is needed let us know. (Just a note since the CRAN deadline is 2 days from now).
