### ISSUE TITLE
Choose parameters for EBE plots

### ISSUE THREAD

**Issue by tmss1** [ggPMXdevelopment/ggPMX#292]
This is more a feature enquiry or request. Is it possible to select parameters for EBE plots, especially when there are many parameters? For example:

![image](https://user-images.githubusercontent.com/32617414/201400242-fd98124a-6785-4853-be35-c79b58de2f86.png)

**Comment by tynsci** [comment]
**Yes** it is possible to do so using below syntax style:

```{r}
pmx_plot_eta_cats(
    ctr,
    effects=list(
      levels=c("ka", "V"),
      labels=c("Absorption_rate", "V")
    )
  )
```

### Forthcoming
- pull request with test that it works and required change to filtering logic
