### ISSUE TITLE
Review Tomas: Inconsistent controller behaviour with BLOQ data in plots 

### ISSUE THREAD

**Issue by tmss1** [ggPMXdevelopment/ggPMX#294]
**Describe the bug**
After setting the controller for the plotting of BLOQ data, the default behaviours of different residual plot functions are different. The standalone residual plot functions (e.g.,`pmx_plot_npde_time()`) would not follow the settings in the controller for BLOQ data and require additional parameters for control, while some other wrapper functions (e.g., `pmx_plot_cats("npde_time")`) would. The inconsistent behaviour is making it very easy to make mistake when plotting and miss these BLOQ data inadvertently. 

The same appears to be true for at least these plots:
`pmx_plot_dv_pred()`
`pmx_plot_dv_ipred()`
`pmx_plot_npde_pred()`
`pmx_plot_npde_time()`
`pmx_plot_iwres_time()`
`pmx_plot_iwres_ipred()`

**Example**
When the controller is set to not showing BLOQ data be default:
`ctr = pmx_mlxtran(file_name=mlxfpath, bloq=pmx_bloq(cens="CENS", show=FALSE))`

This should not show BLOQ data but it does:
`ctr %>% pmx_plot_npde_time()`
![image](https://user-images.githubusercontent.com/32617414/201619954-fa79caf9-86d8-4347-a469-a040de9cb6da.png)

And requires additional control:
`ctr %>% pmx_plot_npde_time(bloq=bloq0)`
![image](https://user-images.githubusercontent.com/32617414/201620040-312a149c-693b-4380-b86b-10a00670856f.png)

While other wrapper functions would follow the controller and not show the BLOQ data:
`ctr %>% pmx_plot_cats("npde_time")`:
![image](https://user-images.githubusercontent.com/32617414/201620597-70a03bf6-4e0c-4882-8c5c-a970f4459717.png)

And requires additional parameters to plot them:
`ctr %>% pmx_plot_cats("npde_time",bloq=pmx_bloq(cens="CENS", show=TRUE))`
![image](https://user-images.githubusercontent.com/32617414/201620724-4aaaddaa-3d90-4ad9-9e40-c1dfcd5da1a4.png)

**Comment by mattfidler** [comment]
Should be closed by 2f8e70dbaa23f34d0fb3b662a4831d304debd38d
