### ISSUE TITLE
Should iwres_dens and potentially other residual plots only show data exceeding BLOQ

### ISSUE THREAD

**Issue by tynsci** [ggPMXdevelopment/ggPMX#321]
see #267

###### Question
- should default behavior of iwres_dens and potentially other residual plots be that only >= BLOQ data points are shown

###### Motivation
- plots may show empty lines if <BLOQ data are included

**Comment by baltcir1** [comment]
No, residual plots should by default display also data <BLOQ. Not sure to understand why there are empty lines in presence of BLOQ.
