### ISSUE TITLE
Bug for nlmixr2 fits

### ISSUE THREAD

**Issue by mattfidler** [ggPMXdevelopment/ggPMX#323]
**Describe the bug**
The censoring for `nlmixr2` no longer behaves correctly

**To Reproduce**

I re-installed R and nlmixr2 packages, and now `plot()`, `vpcPlot()` can work correctly. 😀 Maybe my nlmixr2 package is the early version.
By using `plot()`. DV verse PRED, IPRED.

![image](https://user-images.githubusercontent.com/514778/213222821-6d9ad514-2a51-47ed-8ba5-52bf6ceefe41.png)
 
The only thing is for ggPMX, the plot of `pmx_plot_dv_pred()` still didnt show correctly.
 
![image](https://user-images.githubusercontent.com/514778/213222878-ded6e599-8d91-4c63-96fe-0b0bc6b231c5.png)

**Comment by tynsci** [comment]
thanks for reporting @mattfidler
- just to confirm the desired behavior is that the plot produced by `pmx_plot_dv_pred()` should look similar to the left-hand plot in the top panel?

**Comment by mattfidler** [comment]
Yes, The censoring information should be captured so it doesn't only have red dots at the limit of quantitation.
