### ISSUE TITLE
No all plots using ggPMX and a Monolix project

### ISSUE THREAD

**Issue by Nathalie06** [ggPMXdevelopment/ggPMX#372]
I am trying to use the new ggPMX version and I have a basic issue I guess.
Using the ggPMX example (project.mlxtran) everything is fine, I have all the plots and the report is fine.
But, using a Monolix example, I can’t obtain all plots. The Monolix example is the “bolusLinear_project.mlxtran”. 

> ctr <- pmx_mlxtran(file_name = "C:/TEMP/Test/bolusLinear_project.mlxtran")
y_obsVsPred file do not exist
y_residuals file do not exist
y_residuals file do not exist
`sim_blq` dataset could not be generated, `sim_blq_npde_iwres` or `sim_blq_y` is missing
No data predictions provided for plot abs_iwres_ipred 
No data predictions provided for plot abs_iwres_time 
No data predictions provided for plot iwres_ipred 
No data predictions provided for plot iwres_time 
No data predictions provided for plot iwres_dens 
No data predictions provided for plot iwres_qq 
No data predictions provided for plot npde_time 
No data predictions provided for plot npde_pred 
No data predictions provided for plot npde_qq 
No data predictions provided for plot dv_pred 
No data predictions provided for plot dv_ipred 
> print(ctr)
 
![image](https://github.com/ggPMXdevelopment/ggPMX/assets/65408543/715c481c-a9f0-48b6-961a-8d3a6f44a451)

Some files seem to be missing but they are not, in C:\TEMP\Test\bolusLinear_project\ChartsData\ObservationsVsPredictions:

 I am sure it is a “stupid” mistake but I don’t know which one ☹.

**Comment by mattfidler** [comment]
I'm unsure what files would be missing or why it thinks they are missing.  However I don't think this is enough information to reproduce the issue.

If you could provide more information maybe we can figure out a fix for your issue

**Comment by mattfidler** [comment]
Closing this for now.
