### ISSUE TITLE
question on update() example found on the website

### ISSUE THREAD

**Issue by nsk64** [ggPMXdevelopment/ggPMX#43]
You are first running cmt2fit.logn with nlmixr()
then you call update() with a proportional model: linCmt()~prop.sd
Where prop.sd comes from (no ini values)?
I tried on my data and get the following:
Error in model(.uif, .lines = .deparse(.x)):
  Could not find a part of the model to modify.

**Comment by mattfidler** [comment]
Can you point to the documentation where you see this..

I believe this is a nlmixr issue

**Comment by nsk64** [comment]
https://nlmixrdevelopment.github.io/nlmixr/articles/xgxr-nlmixr-ggpmx.html#fitting-the-data-with-nlmixr


"Fitting the data with nlmixr"



________________________________
De : Matthew Fidler <notifications@github.com>
Envoyé : mardi 17 décembre 2019 13:26
À : ggPMXdevelopment/ggPMX
Cc : SIMON Nicolas; Author
Objet : Re: [ggPMXdevelopment/ggPMX] question on update() example found on the website (#43)


Can you point to the documentation where you see this..

I believe this is a nlmixr issue

-

**Comment by mattfidler** [comment]
Indeed; I have opened up an issue there.
