### ISSUE TITLE
VPC not plotting after simulx simulation without error message

### ISSUE THREAD

**Issue by combefr1** [ggPMXdevelopment/ggPMX#52]
with simulx, ids are changed to a new ID, starting at 1. 
one should modify the simulated file to revert the original IDs. example of code below:

mysim <- simulx(project=mlxpath,nrep=2)
   simdata = mysim$y3
   simdata <- simdata%>%
      left_join(., mysim$originalId)%>%
      mutate(id = oriId)%>%
      select(-oriId, -newId)

**Comment by mattfidler** [comment]
This package uses `data.table` instead of `dplyr`
