### ISSUE TITLE
What happened to the CRAN version?

### ISSUE THREAD

**Issue by Blaza** [ggPMXdevelopment/ggPMX#56]
Hi,
I was looking forward to testing out the package, but for some reason it's not available on CRAN
https://cran.r-project.org/web/packages/ggPMX/index.html
It says

    Package ‘ggPMX’ was removed from the CRAN repository.
    
    Formerly available versions can be obtained from the archive.
    
    Archived on 2020-04-03 as check problems were not corrected in time.
    
    Please use the canonical form https://CRAN.R-project.org/package=ggPMX to link to this page.`

Do you know what happened? 
Do you plan to fix it?

**Comment by agstudy** [comment]
Hi ,

Thank you for notification. 
 We have submitted a new version to CRAN to resolve the problem.

**Comment by agstudy** [comment]
It is fixed. 1.1 version is on CRAN.
