### ISSUE TITLE
Incorrect help description for pmx_gpar

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#58]
"xlab" and "ylab" are shown as arguments for "labels" in the pmx_gpar function.
They do not work. The arguments that work are "x" and "y".

To be double-checked

(Old ticket #221)

**Comment by sehamsick** [comment]
This is updated, the current documentation for `labels` in `pmx_gpbar` is: 
*list of labels, like title, subtitle, x , y*
