### ISSUE TITLE
VPC: Other independent variable than time

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#60]
Question: How to change the x-axis label for VPC plot? Not always time for example! Could be "weight" instead for example

(Old Ticket # 217)

**Comment by tynsci** [comment]
- syntax to change x-axis label for VPC plot (below)
  - (will add to documentation via a pull request)

### Set custom x- and/or y-axis labels
```{r}
ctr %>% pmx_plot_vpc(labels=c(x="DV axis", y="TIME axis"))
```
