### ISSUE TITLE
Test Irina: Set default computation for shrinkage by using variance (not sd)

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#61]
All shrinkage labels for ggPMX plots use shrinkage that is computed based on SD.

However, Novartis PMX Internal Guidance for model building, evaluation, and qualification recommended the use of shrinkage that is based on variance.

##### Test case:
Monolix2018 with the following example:

```
mlxtran_file = "/USER_EXAMPLES/MLX/2018/8.PKPD/SIMULTANEOUS_USING_LIBRARIES/warfarin_PKPDlibrary_project.mlxtran"
ctr = pmx_mlxtran(file_name = mlxtran_file, endpoint = "2")
```

For example:
- shrinkage of ka = 50% in ggPMX
- shrinkage of ka = 74.9% in Monolix

(Old Ticket #220)

**Comment by baltcir1** [comment]
ok, works.
