### ISSUE TITLE
IWRES Quantile plot

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#63]
- Use.labels = T and cats.labels do not work.
- Does not work properly to change axes ranges.
- When using strat.color, some extra points in black appear.
- strat.facet is not effective;
- BLOQ points not shown in a different color.

```
ctr <- theophylline()
max.iwres <- 3
ctr %>% pmx_plot_iwres_qq(
  strat.color = "SEX", 
  cats.labels = list(SEX=c("0"="M","1"="F")), use.labels = TRUE, 
  ranges = list(x = c(-max.iwres*1.05, max.iwres*1.05), y = c(-max.iwres*1.05, max.iwres*1.05)) ,  
  hline = list(yintercept = 0, color = "black", size = 0.25), 
  vline = list(xintercept = 0, color = "black", size = 0.25), 
  use.identity_line = F,
  identity_line = list (color = "red", linetype = 3))
```
Additional issues:

- strat.facet is not effective;
- identity line not shown by default;
- BLOQ points not shown in a different color.

Response from Amine Gassem:

- atrat facetting is working and
- should set labelling in pmx_settings level
- there is no identity_line but ``reference_line`

```
ctr <- theophylline(
  pmx_settings(cats.labels = list(SEX=c("0"="M","1"="F")), 
               use.labels = TRUE)
)
                      
ctr %>% pmx_plot_iwres_qq(
  strat.facet = "SEX", 
  reference_line = list (color = "red", linetype = 3)) 
```

Further investigation:

- strat.facet is still not effective in my testing.
- When using strat.color, some extra points still appear in black.
- The "reference" line is not relevant and actually misleading for a QQ plot.
- Identity line not shown by default.
- The issues with BLQ points and ranges still remain (as well as hline, vline).

(Old Ticket #237)

**Comment by tynesjo** [comment]
Failed to reproduce the reported bug **strat error does not work**.

```r
ctr <- theophylline(
  settings=pmx_settings(
    cats.labels=list(SEX=c("0"="M","1"="F")), 
    use.labels = TRUE,
    use.identity_line=FALSE,
    identity_line = list (color = "red", linetype = 3),
    reference_line = list (color = "red", linetype = 3)
  )
)

# Issue: facet not working (Failed to reproduce) 
p0a <-
  ctr %>%
  pmx_plot_iwres_qq(
    #  strat.facet = "SEX", 
  reference_line=list(color="red", linetype=3)
  ) 

p0b <-
  ctr %>%
  pmx_plot_iwres_qq(
  strat.facet = "SEX", 
  reference_line=list(color="red", linetype=3)
) 

```
here `p0a` yields no facets:
![p0a](https://user-images.githubusercontent.com/3072895/98222544-debd8200-1f48-11eb-9632-dc730a7bedab.png)

while `p0b` does yield facets:
![p0b](https://user-images.githubusercontent.com/3072895/98222573-e715bd00-1f48-11eb-9024-5c3e3665debf.png)

**Comment by tynesjo** [comment]
Regarding the reported bugs **no reference line for this plot**:
as show by the following code snippets and outputs,
`is.reference_line` has to be explicitly set to `TRUE` for a reference line to be plotted.

```r
p1a <-
  ctr %>%
  pmx_plot_iwres_qq(
    strat.facet = "SEX",
#    is.reference_line=TRUE,
    is.identity_line=TRUE,
    identity_line=list(color="red", linetype=3),
    reference_line=list(color="red", linetype=3)
  )

p1b <-
  ctr %>%
  pmx_plot_iwres_qq(
    strat.facet = "SEX",
    is.reference_line=TRUE,
    is.identity_line=FALSE,
    identity_line=list(color="red", linetype=3),
    reference_line=list(color="goldenrod", linetype=3)
  )
```

(using the control object from the previous comment)

here `p1a` shows no reference line:

![p1a](https://user-images.githubusercontent.com/3072895/98223947-bc2c6880-1f4a-11eb-8e16-db79e34f124c.png)

whereas `p1b`  does show one, (as expliticly asked for):
![p1b](https://user-images.githubusercontent.com/3072895/98223964-c2224980-1f4a-11eb-80f6-ee9455873e57.png)

**Comment by tynesjo** [comment]
Regarding the reported bug that **identity line graphical parameters cannot be customized** e.g. color and linetype.

Failed to reproduce this bug.

Below is a code snippet and resulting graphical output which shows customization working.

```r
ctr %>%
pmx_plot_iwres_qq(
  strat.facet = "SEX",
  is.identity_line=TRUE,
  identity_line=list(color="pink", linetype=4, size=2)
)
```

Resulting graphical output:
![p2](https://user-images.githubusercontent.com/3072895/98224884-f0545900-1f4b-11eb-8777-4aac2953c54b.png)

**Comment by tynesjo** [comment]
Regarding the reported bug that **Adding stratificiation color leads to extra points on plot**.

Failed to reproduce this bug.

Below is a code snippet and resulting graphical outputs:

```r
p3a <-
  ctr %>%
  pmx_plot_iwres_qq(
    strat.facet = "SEX",
    strat.color = "SEX"
  )

p3b <-
  ctr %>%
  pmx_plot_iwres_qq(
    strat.facet = "SEX",
    is.reference_line=FALSE
  )
```

Here `p3a` yields:

![p3a](https://user-images.githubusercontent.com/3072895/98225494-acae1f00-1f4c-11eb-9be1-e9cc4cdeb7e0.png)

and, `p3b` yields:
![p3b](https://user-images.githubusercontent.com/3072895/98225526-b46dc380-1f4c-11eb-8138-5df880991ef5.png)

**Comment by tynesjo** [comment]
Regarding the reported bug that *imposing x-axis ranges do not take effect**:
they take effect but only on eliminating data from the plot, not setting the limits of the x axis:

```r
p8a <-
  ctr %>%
  pmx_plot_iwres_qq(
    ranges=list(
      x=c(-1L, 1L),
      y=c(-1L, 1L)
      ),
    discrete=FALSE
  )

p8b <-
  ctr %>%
  pmx_plot_iwres_qq()
```

Here `p8a` yields:
![p8a](https://user-images.githubusercontent.com/3072895/98226029-60171380-1f4d-11eb-938b-cdb0eca62f37.png)

and `p8b` yields:
![p8b](https://user-images.githubusercontent.com/3072895/98226040-66a58b00-1f4d-11eb-93f0-2d5239e30eb5.png)


@biethbr1 is this the desired behavior?

**Comment by tynesjo** [comment]
Regarding the reported bug that **style of hline is not configurable**:

Failed to reproduce. Please see below example of two different plots with hline style settings taking effect:

```r
p9a <-
  ctr %>%
  pmx_plot_iwres_qq(
    is.hline=TRUE,
   hline = list(yintercept=0, color="blue", size=3)
  )

p9b <-
  ctr %>%
  pmx_plot_iwres_qq(
    is.hline=TRUE  
  )

```

Here `p9a` yields:
![p9a](https://user-images.githubusercontent.com/3072895/98226678-41654c80-1f4e-11eb-8b23-857052d7f620.png)

whereas `p9b` yields:

![p9b](https://user-images.githubusercontent.com/3072895/98226695-488c5a80-1f4e-11eb-8502-0be92f60d7da.png)

**Comment by tynesjo** [comment]
Regarding the reported bug that **style of vline is not configurable**.

This bug was found to be due to a missing feature: vline was not an implemented layer for QQ plots.

The feature has not been implemented in the issue branch (pull request TBA); resulting in the following functionality:

```r
p10a <-
  ctr %>%
  pmx_plot_iwres_qq(
    is.vline=TRUE,
    vline = list(xintercept=0, color="blue", size=3)
  )

p10b <-
  ctr %>%
  pmx_plot_iwres_qq(
    is.vline=TRUE,
    vline = list(xintercept=0)
  )
```

Here `p10a` yields:

![p10a](https://user-images.githubusercontent.com/3072895/98228554-a15cf280-1f50-11eb-935a-46184bc36452.png)

whereas `p10b` yields:

![p10b](https://user-images.githubusercontent.com/3072895/98228575-a7eb6a00-1f50-11eb-8f6b-a71342f8a0aa.png)

**Comment by tynesjo** [comment]
Regarding the reported bug that **BLOQ points should be a different color**.

This is not a bug, but rather due to the fact that no BLOQ layer has been implemented for QQ pplots.

Suggest creating a feature request if it is desirable to have this functionality.

**Comment by tynsci** [comment]
- bugs not reproducible
- vline style configuration was added through #143 
- if BLOQ layer is a desired feature for QQ plots, please feel free to create an _enhancement_ issue for that @biethbr1
