### ISSUE TITLE
Possibility to filter data by categorical covariate?

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#64]
Can we have an option like that?

`ctr %>% pmx_filter(data_set = "prediction", SEX==1)`

(Old Ticket #245)

**Comment by tynsci** [comment]
**Yes** this is possible.

##### Code example

```
library(ggPMX)
ctr <- theophylline()
count_by_sex <- . %>%  {.[["data"]][["predictions"]][, .(count = .N), by = SEX]}
print(count_by_sex(ctr))
ctr %>% pmx_filter(data_set = "prediction", SEX == 1)
print(count_by_sex(ctr))
```

- This leads to the following count by sex for data before applying the categorical data filter:
```
   SEX count
1:   1   420
2:   0   180
```

- corresponding count after applying filter:
 ```

   SEX count
1:   1   420

```
