### ISSUE TITLE
Weird appearance for EBE vs continuous covariates plots

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#67]
Need to use the same default as pmx_plot_eta_cats where:

Number of rows = number of parameters

Number of columns = number of continuous covariates

to allow for shared axes ranges and labels.

![image](https://user-images.githubusercontent.com/24472172/81861614-cf94e300-9568-11ea-81ee-38aad73a6508.png)

(Old Ticket #241)

**Comment by KZRKZR** [comment]
Hi @biethbr1 
This code 
```
mlxpath <- file.path(system.file(package = "ggPMX"),
                               "testdata","1_popPK_model","project.mlxtran")
ctr <- pmx_mlxtran(mlxpath, config = "standing")


ctr %>% pmx_plot_eta_cats(labels = list(title = "EBE vs discrete covariates"))
ctr %>%  pmx_plot_eta_conts(labels = list(title = "EBE vs continuous covariates"))
```
returns
![image](https://user-images.githubusercontent.com/10551498/99260345-ec65e800-2823-11eb-98b0-9cf669532c36.png)
could you explain in details what you expected to see on the continuous covariates chart

**Comment by biethbr1** [comment]
It works now. Thanks!
