### ISSUE TITLE
Stratification of individuals by specific group have error

### ISSUE THREAD

**Issue by biethbr1** [ggPMXdevelopment/ggPMX#79]
Bug with existing modeling dataset - cannot be shared for confidentiality reason

To follow-up with Souvik

(Old Ticket #166)

**Comment by KZRKZR** [comment]
Hi @biethbr1 
Could you please provide a reproducible example for this issue?
Thank you!

**Comment by tynesjo** [comment]
Please feel free reopen as and when a reprodusible example becomes available..
