### ISSUE TITLE
parameter table

### ISSUE THREAD

**Issue by combefr1** [ggPMXdevelopment/ggPMX#80]
Hi guys 
Some suggestions following your newsletter about the parameter table: 
- add confidence interval 
- add a footnote with equations for RSE + CI
- remove "_pop" in the parameters labels
- change column titles to lower case, with legible names, this way it can directly be copied in word...
- for covariates, can we propose to automatically compute examples of parameter values. if I take your example with age on clearance, you could compute Cl for Q5, median and Q95 of observed ages? it can be complicated when several covs are included, but maybe worth considering. 

best
Francois

**Comment by baltcir1** [comment]
Linked to another suggestion to add parameter table.

**Comment by tynsci** [comment]
- parameter table is being updated by #328 which addresses #203 
  - (adding correlations)

- the above suggestions are not reflected in the new merge request
- @baltcir1 @biethbr1 should any/all of the changes listed above be implemented?

**Comment by baltcir1** [comment]
Thanks for following up on this request. Here are my suggestions for the points above:
- add confidence interval --> not at this stage (it would be nice, but it would require further computations, possibly bootstrap)
- add a footnote with equations for RSE + CI --> not if above bullet not implemented
- remove "_pop" in the parameters labels --> this can be done
- change column titles to lower case, with legible names, this way it can directly be copied in word... --> already implemented
- for covariates, can we propose to automatically compute examples of parameter values. if I take your example with age on clearance, you could compute Cl for Q5, median and Q95 of observed ages? it can be complicated when several covs are included, but maybe worth considering. --> this is usually done by simulation separately from GoF report.

**Comment by tynsci** [comment]
Thank you @baltcir1
- will make sure the 3rd and 4th bullet points (labels and column titles) are incorporated in #328

**Comment by tynsci** [comment]
Note on column names (stated as already implemeted @baltcir1 )
- these are currently "Parameter" "Value" "RSE" "Shrinkage"
- just to to confirm they will need to be changed to "parameter" "value "rse" "shrinkage"
  - it has not been implemented previously

**Comment by baltcir1** [comment]
Dear Johannes,
please keep the column names as they are ("Parameter" "Value" "RSE" "Shrinkage"). 
THanks

**Comment by combefr1** [comment]
FYI, Monolix 2023 will also contains omega computed as CV%
