### ISSUE TITLE
Shrink option does not work

### ISSUE THREAD

**Issue by KZRKZR** [ggPMXdevelopment/ggPMX#89]
`ctr %>% pmx_plot_eta_box(shrink = list("sd"))`
This should be verified empirically.
The problem, if it exists, lies in the pmx_update_plot function.

The resulting plot of call without params and call with implicit value for shrink is different for box:
```
ctr <- theophylline()
ctr %>% pmx_plot_eta_box()
ctr %>% pmx_plot_eta_box(shrink = list("sd"))
```
and the same for hist:

```
ctr <- theophylline()
ctr %>% pmx_plot_eta_hist()
ctr %>% pmx_plot_eta_hist(shrink = list("sd"))
```

**Comment by agstudy** [comment]
it works fine , just your call is not correct 

```
ctr %>% pmx_plot_eta_box( shrink=list(fun = "var"))
ctr %>% pmx_plot_eta_box( shrink=list(fun = "sd"))
ctr %>% pmx_plot_eta_hist( shrink=list(fun = "sd"))
ctr %>% pmx_plot_eta_hist( shrink=list(fun = "var"))
```

Here i recommand :
 -  enhance the documentation 
 - use helpful function to set the shrinkage parameters( à la pmx_plo_vpc) for example shrink=pmx_shrink())

**Comment by KZRKZR** [comment]
Thanks!

- enhance the documentation - **add examples of changing shrink option to ggPMX-guide?**
- use the helpful function to set the shrinkage parameters( à la pmx_plo_vpc) for example shrink=pmx_shrink()) - **do you mean simple wrapper which could be used like:**

```
ctr %>% pmx_plot_eta_hist( shrink=pmx_shrink("var"))
ctr %>% pmx_plot_eta_hist( shrink=pmx_shrink("sd"))
```

**Comment by agstudy** [comment]
yes , but pmx_shrink is a function taht will use named parameters :+1: 

```
ctr %>% pmx_plot_eta_hist( shrink=pmx_shrink(fun= "var"))
ctr %>% pmx_plot_eta_hist( shrink=pmx_shrink(fun="sd"))
```

**Comment by KZRKZR** [comment]
Good, will close this issue and create a new one regarding proposed changes.
