### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by KZRKZR** [ggPMXdevelopment/ggPMX#91]
https://codecov.io/gh/ggPMXdevelopment/ggPMX
get to over 90% test coverage

**Comment by biethbr1** [comment]
How much coverage shall we aim at?

**Comment by mattfidler** [comment]
We should probably test the main functions first.  It seems that some of the things may need to be skipped on cran.  Currently reports, VPCs, NONMEM, nlmixr are not well tested

**Comment by mattfidler** [comment]
Also bugs that are fixed should ideally have tests so they don't reoccur.
