### ISSUE TITLE
rm_dir function doesn't work on Windows

### ISSUE THREAD

**Issue by KZRKZR** [ggPMXdevelopment/ggPMX#97]
rm_dir under the hood uses:

`system(sprintf("rm -r %s", to_remove))`,

which doesn't work  on Windows and return 127 code.

We could  use unlink:

 unlink(out_,recursive = TRUE, force = TRUE)

**Comment by ggPMXdevelopment** [comment]
Where is rmdir used? Is it in pmx_report?

**Comment by KZRKZR** [comment]
Yes, it is in pmx_report to clear ggpmx_GOF output folder.

**Comment by sehamsick** [comment]
Thanks for the tipp! The code `system(sprintf("rm -r %s", to_remove))` will be replaced by `unlink(to_remove,recursive = TRUE, force = TRUE)` for the next version.
