### ISSUE TITLE
pmx_report failed with npage=1

### ISSUE THREAD

**Issue by KZRKZR** [ggPMXdevelopment/ggPMX#98]
```
  ctr <- theophylline()
  ctr %>% pmx_report(
    name="report23",
    save_dir = "E:/test",
    template="individual",
    format="both",
    npage=1
  )
```
return

Error: Plot(s) were registered within ggPMX but were not rendered. Footnotes may be wrong.

and in word report looks like:
[report23.docx](https://github.com/ggPMXdevelopment/ggPMX/files/4741916/report23.docx)

After this error, the previous calls, which work fine also return error:

  ctr %>% pmx_report(
    name="report23",
    save_dir = "E:/test",
    template="individual",
    format="both",
    npage=3:4
  )
Error: Plot(s) were registered within ggPMX but were not rendered. Footnotes may be wrong.
At the same time, the report looks good.

**Comment by tynesjo** [comment]
fixed by #141
